---
title: Assert vs raise
author: Max Kovalovs
date: '2018-09-20'
slug: assert-vs-raise
categories: ["python"]
tags: []
---

# Intro

In a perfect world nobody would need exceptions in their programs, however, often unexpected things happen during runtime - invalid values get submitted, users make typos when writing paths and so on. To handle this developers use exceptions - upon encountering an abnormal situation (e.g. division by zero) the normal execution flow is interrupted, until the exception is dealt with. In python, doing this would look like this:


```{r engine='bash', comment='', echo=FALSE}
cat assert-vs-raise/pizza_slice_raise.py
```

```{r engine='bash', comment='', echo=FALSE}
python assert-vs-raise/pizza_slice_raise.py || true
```

However, python has assertion statements, which do a similar thing:

```{r engine='bash', comment='', echo=FALSE}
cat assert-vs-raise/pizza_slice_assert.py
```

```{r engine='bash', comment='', echo=FALSE}
python assert-vs-raise/pizza_slice_assert.py || true
```

The error message raised was different, but the code is much more readable.
